### ISSUE TITLE
Fix Python version issues for tox

### ISSUE THREAD

**Issue by beheh** [HearthSim/hearthsim-vagrant#5]
In hsreplaynet, tox on Vagrant fails with the following error:

```
ERROR: InvocationError: Failed to get version_info for python3.6: b"pyenv: python3.6: command not found\n\nThe `python3.6' command exists in these Python versions:\n  3.6.2\n\n"
```

Apparently we're missing a line here:

https://github.com/HearthSim/hearthsim-vagrant/blob/215f0998afa58e2408e77f6f039817add1d495a7/scripts/provision_user.sh#L27-L30

**Comment by jleclanche** [comment]
Should be fixed now
